# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10FcAs4bBC7J0fhXtiQUe-6GUIST8idcv
"""

import streamlit as st

st.title('mi primera aplicacion web con streamlit')
st.write('esta es una aplicacion web de ejemplo utilizando estreamlit.')
